<?php
/* @var $paymentProfile CoreValue_Acim_Model_Profile_Payment */
/* @var $this CoreValue_Acim_Block_Card */
$paymentProfile         = $this->getPaymentProfile();
/* @var $acimEntity Varien_Object */
$acimEntity             = $this->retrievePaymentProfile();
?>
<div class="page-title">
    <?php if ($paymentProfile->getId()): ?>
    <h2 class="legend"><?php echo $this->__('Details for') ?> XXXX-XXXX-XXXX-<?php echo $paymentProfile->getCcLast4(); ?></h2>
    <?php else: ?>
    <h2 class="legend"><?php echo $this->__('Adding new Credit Card') ?></h2>
    <?php endif; ?>
</div>

<?php if ($paymentProfile->getId()): ?>
<em><?php echo $this->__('Keep XXXX in case if you do not want to modify CC number, CVV/CID or Expiration Date.'); ?></em>
<?php endif; ?>

<form method="post" name="add-edit-cc-form" id="add-edit-cc-form" action="<?php echo $this->getUrl('acimprofiles/index/update', ['id' => $paymentProfile->getId()]) ?>">
    <?php echo $this->getBlockHtml('formkey')?>
    <ul class="form-list">
        <li>
            <label for="number" class="required"><em>*</em><?php echo $this->__('Credit Card Number'); ?></label>
            <div class="input-box">
                <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="number" id="number" value="<?php echo $acimEntity->getCreditCard()->getNumber(); ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="exp_date" class="required"><em>*</em><?php echo $this->__('Credit Expiration Date'); ?></label>
            <div class="input-box">
                <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="exp_date" id="exp_date" value="<?php echo $acimEntity->getCreditCard()->getExpDate(); ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="cvv" class="required"><em>*</em><?php echo $this->__('CVV/CID'); ?></label>
            <div class="input-box">
                <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="cvv" id="cvv" value="<?php echo $paymentProfile->getId() ? 'XXXX' : ''; ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="cc_type"><?php echo $this->__('Credit Card Type'); ?>: <?php echo $acimEntity->getCreditCard()->getType(); ?></label>
            <div class="input-box">
                <select id="cc_type" name="cc_type" class="required-entry">
                    <option value=""><?php echo $this->__('--Please Select--'); ?></option>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $paymentProfile->getCcType()): ?> selected<?php endif; ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li>&nbsp;<b><?php echo $this->__('Billing Address'); ?></b></li>
        <li>
            <label for="first_name" class="required"><em>*</em><?php echo $this->__('First Name'); ?></label>
            <div class="input-box">
                <input type="text" name="firstname" id="first_name" value="<?php echo $acimEntity->getBillTo()->getFirstname(); ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="last_name" class="required"><em>*</em><?php echo $this->__('Last Name'); ?></label>
            <div class="input-box">
                <input type="text" name="lastname" id="last_name" value="<?php echo $acimEntity->getBillTo()->getLastname(); ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="phone" class="required"><em>*</em><?php echo $this->__('Phone Number'); ?></label>
            <div class="input-box">
                <input type="text" name="phone" id="phone" value="<?php echo $acimEntity->getBillTo()->getPhone(); ?>" class="input-text required-entry validate-phoneLax" />
            </div>
        </li>
        <li>
            <label for="fax"><?php echo $this->__('Fax Name'); ?></label>
            <div class="input-box">
                <input type="text" name="fax" id="fax" value="<?php echo $acimEntity->getBillTo()->getFax(); ?>" class="input-text validate-phoneLax" />
            </div>
        </li>
        <li>
            <label for="company"><?php echo $this->__('Company'); ?></label>
            <div class="input-box">
                <input type="text" name="company" id="company" value="<?php echo $acimEntity->getBillTo()->getCompany(); ?>" class="input-text" />
            </div>
        </li>
        <li>
            <label for="address" class="required"><em>*</em><?php echo $this->__('Address'); ?></label>
            <div class="input-box">
                <input type="text" name="address" id="address" value="<?php echo $acimEntity->getBillTo()->getAddress(); ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="city" class="required"><em>*</em><?php echo $this->__('City'); ?></label>
            <div class="input-box">
                <input type="text" name="city" id="city" value="<?php echo $acimEntity->getBillTo()->getCity(); ?>" class="input-text required-entry" />
            </div>
        </li>
        <li>
            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province'); ?></label>
            <div class="input-box">
                <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                    //<![CDATA[
                    $('region_id').setAttribute('defaultValue',  "<?php echo $acimEntity->getBillTo()->getRegionId() ?>");
                    //]]>
                </script>
                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($acimEntity->getBillTo()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
            </div>
        </li>
        <li>
            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip'); ?></label>
            <div class="input-box">
                <input type="text" name="zip" id="zip" value="<?php echo $acimEntity->getBillTo()->getZip(); ?>" class="input-text required-entry validate-zip" />
            </div>
        </li>
        <li>
            <label for="country" class="required"><em>*</em><?php echo $this->__('Country'); ?></label>
            <div class="input-box">
                <?php echo $this->getCountryHtmlSelect() ?>
            </div>
        </li>
    </ul>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getUrl('acimprofiles'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Credit Card')) ?>" class="button"><span><span><?php echo $this->__('Save Credit Card') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
    var customForm = new VarienForm('add-edit-cc-form');
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    //]]>
</script>