<?php
/* @var $this CoreValue_Acim_Block_Form */
$_code = $this->getMethodCode();

$customer           = Mage::getBlockSingleton('adminhtml/sales_order_create_form_account');
$paymentProfiles    = $this->getPaymentProfiles($customer->getFormValues()['id'], $customer->getFormValues()['email']);
?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">

    <?php if(isset($paymentProfiles) && $paymentProfiles->count()) :?>
    <div>
        <input type="radio" name="p_option" onclick="showSelect()" id="payment_form_<?php echo $_code ?>_select_label" value="0" checked />
        <label for="payment_form_<?php echo $_code ?>_select_label"><?php echo $this->__('Select Credit Card') ?></label>
    </div>

    <div class="form-list" id="payment_form_<?php echo $_code ?>_select">
        <div class="input-box">
            <select id="<?php echo $_code ?>_payment_id" name="payment[payment_id]" class="required">
                <option value=""><?php echo $this->__('Please, select saved CC from the list') ?></option>
                <?php foreach($paymentProfiles as $cc){?>
                    <option value="<?php echo $cc->getPaymentId(); ?>">XXXX-XXXX-XXXX-<?php echo $cc->getCcLast4(); ?></option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div>
        <input type="radio" name="p_option" onclick="showEnter()" id="payment_form_<?php echo $_code ?>_new_label" value="1" />
        <label for="payment_form_<?php echo $_code ?>_new_label"><?php echo $this->__('Enter Credit Card') ?></label>
    </div>
    <?php endif; ?>

    <ul class="form-list" id="payment_form_<?php echo $_code ?>_new"<?php if(isset($paymentProfiles) && $paymentProfiles->count()) :?> style="display:none;"<?php endif; ?>>
        <li>
            <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]">
                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Credit Card Number')) ?>" value="" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Card Verification Number')) ?>" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                </div>
            </div>
        </li>
    </ul>
</div>

<script>
    showSelect = function () {
        $('payment_form_<?php echo $_code ?>_select').show();
        $('payment_form_<?php echo $_code ?>_new').hide();
    }
    showEnter = function () {
        $('payment_form_<?php echo $_code ?>_new').show();
        $('payment_form_<?php echo $_code ?>_select').hide();
        $$('#<?php echo $_code ?>_payment_id option')[0].selected = true;
    }
</script>